### ISSUE TITLE
Focus text field only works in y direction

### ISSUE THREAD

**Issue by LukeDefeo** [michaeltyson/TPKeyboardAvoiding#122]
I have a form which looks like 

_______  1
_______   2
     __ __   3
_______   4

It correctly goes to the left box on line 3 then right box but next goes back to the left box around and around. It would be nice it it looked at the cells x position too.

Something like find the next one down but if there is one to the right of you then go to that, otherwise go down?

Thanks

Luke

**Comment by AnthonyMDev** [comment]
I believe I've fixed this with #175. 
Would you mind trying out my fork with that pull request implemented and let me know if this solves your problem?

**Comment by michaeltyson** [comment]
Just looking at this now, Anthony - cheers

**Comment by AnthonyMDev** [comment]
@michaeltyson You're one of the good ones. ;) Thanks

**Comment by michaeltyson** [comment]
=)

No joy, though, I'm afraid; this breaks the sample app. I'm going to have a look at the original algorithm, but it'd help heaps if you could whip up a quick sample app or something, with the specific geometry that's causing the problem.
