### ISSUE TITLE
Skip disabled textFields

### ISSUE THREAD

**Issue by dumareckii** [michaeltyson/TPKeyboardAvoiding#128]
I disabled a few fields and I can not go to the next field by pressing return button. I solved the problem by editing the method : 
         - (void)TPKeyboardAvoiding_findTextFieldAfterTextField:(UIView*)priorTextField beneathView:

I add this code :
              UITextField * textField = (UITextField *)childView;
              if (!textField.enabled) continue;

after this line :
              if ( childView.hidden ) continue;

Is it  possible to add it to your repository , or have another solution to this problems ?

**Comment by elpatxificador** [comment]
Congratulations on the project.

It's a good idea to add this feature.

You could also add Previous TextField Focus???

**Comment by AnthonyMDev** [comment]
+1
I'm having this issue as well. Seems like an easy fix. Can we get this added?

Thank you!

**Comment by michaeltyson** [comment]
Certainly, if someone wants to make a pull request, I'll accept it.

**Comment by AnthonyMDev** [comment]
I'll handle this right now. @dumareckii thanks for the issue.
@michaeltyson you'll see a pull request shortly.

**Comment by AnthonyMDev** [comment]
@michaeltyson The pull request has been made!

**Comment by michaeltyson** [comment]
Lovely, nice one! Merged.

**Comment by AnthonyMDev** [comment]
Thanks! When should we expect a new version of the pod for use in CocoaPods?

**Comment by michaeltyson** [comment]
Now =)
