### ISSUE TITLE
Ability to scroll before keyboard popup

### ISSUE THREAD

**Issue by jkunzelman** [michaeltyson/TPKeyboardAvoiding#145]
I have instance where I would like the view to be scrollable on first load before any field becomes first responder. Right now scrolling seems to be locked when the view is opened. Once a field is selected the view is scrollable. Is it possible to have the view scrollable initially?

**Comment by shreeshecommstreet** [comment]
Same question of me too.

**Comment by shreeshecommstreet** [comment]
May be you have called keyboard notification in view controllers too. It will prevent the use of this

**Comment by cbowns** [comment]
No need! Just set your scrollview's `contentInset` as needed. That's all that `TPKeyboardAvoiding` is doing, after all.

**Comment by cvlehe** [comment]
Just add the following line of code 
`    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        scrollView.contentSizeToFit()
        scrollView.scrollEnabled = true
    }`

You have to connect the scrollView to the view controller.

**Comment by cbowns** [comment]
@jkunzelman Leave a comment if this is still an issue for you.
