### ISSUE TITLE
Dismiss Keyboard in UIViewController

### ISSUE THREAD

**Issue by shehzadq** [michaeltyson/TPKeyboardAvoiding#146]
How can i achieve same functionality in UIViewController with UIView like we in UIScrollView.

I have a UIViewController with UIView which have textfields.

**Comment by cbowns** [comment]
This project is inseparably tied to UIScrollView. You could manually manipulate your UIView's `bounds.origin` with an animation to accomplish the same basic behaviour as UIScrollView.
