### ISSUE TITLE
Can not use the library when using customer UITableView implementations

### ISSUE THREAD

**Issue by yasirmturk** [michaeltyson/TPKeyboardAvoiding#151]
It should work without subclassing because when using custom implementations of `UITableView` or `UIScrollView`, one can not inherit from TP

**Comment by cbowns** [comment]
to do this, one would need to reimplement all of the work that `TPKeyboardAvoiding` does in a swizzling class that swaps in implementations on a chosen class selector.

non-trivial, but definitely possible.

**Comment by michaeltyson** [comment]
I think this is one for the 'too hard basket'.
