### ISSUE TITLE
Commit 7a89fc7 breaks contentInset recovery!

### ISSUE THREAD

**Issue by Pash237** [michaeltyson/TPKeyboardAvoiding#152]
Commit “add support for third-party keyboard(fix #148)” breaks contentInset recovery – after keyboard is hidden insets are not restored and scrollView goes under the Navigation Bar (on iOS 7+).

This is clearly seen in the code – `priorInset` is never set:
```
    state.keyboardVisible = YES;
    if ( !state.keyboardVisible ) {
        state.priorInset = self.contentInset;
        ...
    }
```

**Comment by Pash237** [comment]
This must be somewhat high priority, because most ScollViews/TableViews are used fullscreen, with contentInsets for NavigationBar on iOS 7+. This issue makes TPKeyboardAvoiding unusable :(

**Comment by michaeltyson** [comment]
Does the obvious change:

```
diff --git a/TPKeyboardAvoiding/UIScrollView+TPKeyboardAvoidingAdditions.m b/TPKeyboardAvoiding/UIScrollView+TPKeyboardAvoidingAdditions.m
index 97120e9..954b1eb 100644
--- a/TPKeyboardAvoiding/UIScrollView+TPKeyboardAvoidingAdditions.m
+++ b/TPKeyboardAvoiding/UIScrollView+TPKeyboardAvoidingAdditions.m
@@ -60,14 +60,14 @@ static const int kStateKey;
     }
     
     state.keyboardRect = keyboardRect;
-    state.keyboardVisible = YES;
     
     if ( !state.keyboardVisible ) {
         state.priorInset = self.contentInset;
         state.priorScrollIndicatorInsets = self.scrollIndicatorInsets;
         state.priorPagingEnabled = self.pagingEnabled;
     }
-
+    
+    state.keyboardVisible = YES;
     self.pagingEnabled = NO;
         
     if ( [self isKindOfClass:[TPKeyboardAvoidingScrollView class]] ) {
```

fix this?

**Comment by michaeltyson** [comment]
I got impatient; committed as SHA b7f262470f737d883a266624111759a45318a5ce. Pretty sure it should fix it. Please let me know ASAP though. I can't reproduce the issue you describe on my end, alas.

**Comment by cristianbica** [comment]
It's fixed for me.

**Comment by Pash237** [comment]
Fixed for me too!
Closed.
