### ISSUE TITLE
How to use TPKeyboardAvoiding in swift 

### ISSUE THREAD

**Issue by kalpesh22m** [michaeltyson/TPKeyboardAvoiding#157]
I want to use in my swift project . could u please suggest me ?. Thanks in advance

**Comment by manumax** [comment]
Hope it helps.

**Comment by rodrigobirriel** [comment]
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by LordNacho** [comment]
Add a bridging header for each of the .h files. Then you can use Storyboard to change the custom class to the relevant class.

**Comment by cbowns** [comment]
These answers seem sufficient. I've used this in several Swift projects without any issues. If you hit a particular problem, please open another issue.

**Comment by rtiwarihr** [comment]
@cbowns I'm facing this 
Unknown class _TtC8Swiftapp28TPKeyboardAvoidingScrollView in Interface Builder file

Few pointers:

Using storyboard
Added the class in bridging header
Verified target membership settings
