### ISSUE TITLE
How can i avoid Hidden Textfield Space when Keyboard Appears

### ISSUE THREAD

**Issue by prasathbabu** [michaeltyson/TPKeyboardAvoiding#163]
i am having 6 text field's.. in that i am programmatically handle the frame, hidden the 5th text field and move the 6th text field to 5th text field position.

While touch on 6 text field,  its moves to original position and their space between 4th and 6th text field position, it takes 5th text field space (that's already hidden).. how can i avoid this ? plz help me with this issue..

**Comment by AnthonyMDev** [comment]
There is already an issue for this. #128. I'm actually going to be making a pull request to fix this today. Please keep up to date with this in the current issue and hold tight!

Thanks.

**Comment by AnthonyMDev** [comment]
Have you tried setting the hidden text field to also be `enabled = false` ?
