### ISSUE TITLE
Initial state error

### ISSUE THREAD

**Issue by MetaImi** [michaeltyson/TPKeyboardAvoiding#164]
Hi

I had an issue when the scrollview scrolls under the navigation bar. I have debugged the code, and discovered this in the keyboardwillshow method: 

state.keyboardVisible = YES;
    
    if ( !state.keyboardVisible ) {
        state.priorInset = self.contentInset;
        state.priorScrollIndicatorInsets = self.scrollIndicatorInsets;
        state.priorPagingEnabled = self.pagingEnabled;
    }

so it will never save the state. If you move the keyboardVisible setter under the if, it will work :)

**Comment by michaeltyson** [comment]
That's weird - are you looking at the latest code? I can't find that in the [latest keyboardWillShow](https://github.com/michaeltyson/TPKeyboardAvoiding/blob/master/TPKeyboardAvoiding/UIScrollView%2BTPKeyboardAvoidingAdditions.m#L64)
