### ISSUE TITLE
Cursor does not advance to the next text field with the same y position

### ISSUE THREAD

**Issue by marcustoy** [michaeltyson/TPKeyboardAvoiding#165]
I have this peculiar problem where I have 3 text fields on the same height level (y-position). When I click "Next", the cursor correctly jumps from the 1st text field to the 2nd. But if I click "Next" again, the cursor does not jump to the 3rd field. Instead it jumps back to the 1st field. And it just keep on jumping back to the 1st field, whenever I wanna jump from the 2nd field to the 3rd field.

Any suggestions on how to solve this?

**Comment by alok1upadhyay** [comment]
Can we see your code, i don't think it have to do any thing with TPKeyboard...have you done some thing like this:

-(BOOL)textFieldShouldReturn:(UITextField*)textField
{
  NSInteger nextTag = textField.tag + 1;
  // Try to find next responder
  UIResponder* nextResponder = [textField.superview viewWithTag:nextTag];
  if (nextResponder) {
    // Found next responder, so set it.
    [nextResponder becomeFirstResponder];
  } else {
    // Not found, so remove keyboard.
    [textField resignFirstResponder];
  }
  return NO; // We do not want UITextField to insert line-breaks.
}

Note: you should never tag any view with tag 0.

**Comment by marcustoy** [comment]
Hi Michael Tyson,

To be frank I have not written any textfield delegate methods or even, any methods at all for the textfields. So there’s no codes to show you.

I just imported your library into my project, assign a scrollview as class TPKeyboardAvoidingScrollView, and embed my view into the scroll view programmatically when my view go through viewDidLoad. No codes have been written, and it has been working wonderfully, except for that particular special case.

I read through your code and particularly drawn to the following section. Could this be the source of the problem, I wonder?


- (void)TPKeyboardAvoiding_findTextFieldAfterTextField:(UIView*)priorTextField beneathView:(UIView*)view minY:(CGFloat*)minY foundView:(UIView* __autoreleasing *)foundView {
    // Search recursively for text field or text view below priorTextField
    CGFloat priorFieldOffset = CGRectGetMinY([self convertRect:priorTextField.frame fromView:priorTextField.superview]);
    for ( UIView *childView in view.subviews ) {
        if ( childView.hidden ) continue;
        if ( ([childView isKindOfClass:[UITextField class]] || [childView isKindOfClass:[UITextView class]]) && childView.isUserInteractionEnabled) {
            CGRect frame = [self convertRect:childView.frame fromView:view];
            if ( childView != priorTextField
                    && CGRectGetMinY(frame) >= priorFieldOffset
                    && CGRectGetMinY(frame) < *minY &&
                    !(fequal(frame.origin.y, priorTextField.frame.origin.y)
                      && frame.origin.x < priorTextField.frame.origin.x) ) {
                *minY = CGRectGetMinY(frame);
                *foundView = childView;
            }
        } else {
            [self TPKeyboardAvoiding_findTextFieldAfterTextField:priorTextField beneathView:childView minY:minY foundView:foundView];
        }
    }
}



Thanks for writing to me personally. Hope to hear from you soon!


Regards,
Marcus Toy

**Comment by michaeltyson** [comment]
Fixed with latest commits
