### ISSUE TITLE
Swift - UITableView freezes when overriding viewDidLayoutSubviews

### ISSUE THREAD

**Issue by gkaimakas** [michaeltyson/TPKeyboardAvoiding#166]
Hello,

I wanted to have my Table view extend to the top of the screen, right under the navigation bar, so I overrode viewDidLayoutSubviews with the following code

    override func viewDidLayoutSubviews() {
        var offset:CGFloat? = self.navigationController?.navigationBar.frame.origin.y
        self.tableView.contentInset = UIEdgeInsets(
            top: 0,
            left: 0,
            bottom: 0,
            right: 0)
    }

But when I click on a table cell that has a UITextField in it and causes the keyboard to appear, the app crashes all the time.

If I remove the above func, everything works fine. Is this a bug?

**Comment by michaeltyson** [comment]
I'm pretty sure this isn't a TPKeyboardAvoiding problem
