### ISSUE TITLE
Resign First Responder when scrolling

### ISSUE THREAD

**Issue by chlebta** [michaeltyson/TPKeyboardAvoiding#170]
Hello, How to hide keyboard, and resign first responder, if user start scrolling

**Comment by jobinkurian** [comment]
@chlebta The UIScrollView in the interface builder has keyboard property which can be changed to "Dismiss on drag".
I hope this will solve your problem.

**Comment by icodebuster** [comment]
@chlebta The UIScrollView in the interface builder has keyboard property which can be changed to "Dismiss on drag".
I hope this will solve your problem.

**Comment by chlebta** [comment]
I'm using `TPKeyboardAvoidingTableView` how to achive this ?

**Comment by icodebuster** [comment]
@chlebta Even tableview has this property please check.

**Comment by chlebta** [comment]
I can't find it , i m creating my tableview programmatically

**Comment by icodebuster** [comment]
@chlebta 
Try this
` [tableView setKeyboardDismissMode:UIScrollViewKeyboardDismissModeOnDrag];`

**Comment by icodebuster** [comment]
@chlebta 
If this is solved please close the issue. :+1:

**Comment by chlebta** [comment]
This is not working always same issue ,

**Comment by michaeltyson** [comment]
Not related to TPKA
