### ISSUE TITLE
Stops working when enabling Auto Layout

### ISSUE THREAD

**Issue by xplatsolutions** [michaeltyson/TPKeyboardAvoiding#171]
I was searching for nice implementations like the one you have, good job!

Unfortunately when I enable Auto Layout in your sample project FirstView.xib it just stopped applying any actions you take with the frames to reposition the View selected.

Of course I added constraints to the Views. And with that it's all about how views are related to each other, we can't no longer think with frames. I'm thinking for a universal solution finding the proper constraint and figuring out the constant;

Any idea what we can start changing to support Auto Layout; it is very important in current projects.

**Comment by michaeltyson** [comment]
Works for me! Try the new sample app.

**Comment by xplatsolutions** [comment]
I see what you mean now. The solution can't work if it's not inside a scroll container (UIScrollView, UITableView, UICollectionView). You changed the sample and there is no ViewController with a plain view and couple UITextField at the bottom that will brought up if keyboard appears.
