### ISSUE TITLE
[maintenance] Appoint a repository maintainer

### ISSUE THREAD

**Issue by cbowns** [michaeltyson/TPKeyboardAvoiding#172]
Hi Michael! I want to help maintain this repo with you. Care to appoint a repo maintainer to help screen issues, etc etc?

**Comment by michaeltyson** [comment]
Hey Christopher - sure thing, I'd appreciate the assistance! Do check with me before merging pull requests, though, for now =)

**Comment by cbowns** [comment]
A+ will do!
