### ISSUE TITLE
FocusNextTextField selecting incorrect text field.

### ISSUE THREAD

**Issue by AnthonyMDev** [michaeltyson/TPKeyboardAvoiding#174]
My view looks like this:

-----1111111-
-----222222--
33333333333
44444444444

Where the numbers each represent a `UITextField`.

When using `focusNextTextField` from text field 1, it focuses on text field 3, completely skipping text field 2.

**Comment by AnthonyMDev** [comment]
I've fixed this issue with #175 
This is mission critical for my work, so I'd appreciate your feedback as soon as you can!  Even if you don't plan on merging my pull request, I'd like to know so that I can create a private Cocoapod from my fork to use for my application. Thank you @michaeltyson !

**Comment by michaeltyson** [comment]
Fixed!
