### ISSUE TITLE
Problem with animation on iOS 9.1

### ISSUE THREAD

**Issue by anton-plebanovich** [michaeltyson/TPKeyboardAvoiding#186]
On iOS 9.1 there is a bug with TPKeyboardAvoiding framework. Steps to reproduce:
1) Open screen with any keyboard avoiding view, for example TPKeyboardAvoidingScrollView and two UITextField. Here is test project https://github.com/anton-plebanovich/TP-framework-iOS-9.1-bug
2) Only working with empty field. Must be at least two fields on screen to reproduce. Press and type something in empty field.
3) Press on other field and text in first field will animate from top-left corner to his position. Can be reproduced only once. Reenter screen to test again.
Bug description:
TPKeyboardAvoiding is animating constraints changes with [self layoutIfNeeded] command in UIScrollView+TPKeyboardAvoidingAdditions.m in TPKeyboardAvoiding_keyboardWillShow: and TPKeyboardAvoiding_keyboardWillHide: methods. This also animate UITextField inner changes for written steps.
Possible hotfixes:
For me removing [self layoutIfNeeded]; or replacing it with [self layoutSubviews]; was a solution.

**Comment by nezhyborets** [comment]
Problem for me too

**Comment by anton-plebanovich** [comment]
Bug was fixed for case when field is changing by press next button, but not for case when pressing other text field manually. I can be wrong, but following helped me:
```
-(void)TPKeyboardAvoiding_scrollToActiveTextField {
    TPKeyboardAvoidingState *state = self.keyboardAvoidingState;
    
    if ( !state.keyboardVisible ) return;

    state.ignoringNotifications = YES; // <=========
    
    CGFloat visibleSpace = self.bounds.size.height - self.contentInset.top - self.contentInset.bottom;
    
    CGPoint idealOffset = CGPointMake(self.contentOffset.x, [self TPKeyboardAvoiding_idealOffsetForView:[self TPKeyboardAvoiding_findFirstResponderBeneathView:self]
                                                               withViewingAreaHeight:visibleSpace]);

    // Ordinarily we'd use -setContentOffset:animated:YES here, but it interferes with UIScrollView
    // behavior which automatically ensures that the first responder is within its bounds
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        
        [self setContentOffset:idealOffset animated:YES];
        state.ignoringNotifications = NO;  // <=========
    });
}
```

**Comment by michaeltyson** [comment]
To be honest, I think this is something Apple need to fix: I noticed the same behaviour on the UICollectionView with TPKeyboardAvoiding completely disabled. Maybe something for bugreport.apple.com?

**Comment by anton-plebanovich** [comment]
I noticed that UICollectionView scrolls strange when selecting UITextField, but it never glitch for me.

**Comment by anton-plebanovich** [comment]
Added collection view to test here https://github.com/anton-plebanovich/TP-framework-iOS-9.1-bug

**Comment by kaylanx** [comment]
Hi Michael,

Are you planning to do a cocoapods release soon with this fix and the `state.ignoringNotifications` changes suggested by Anton?

Andy

**Comment by michaeltyson** [comment]
Ah, thanks for the prod, @kaylanx - done.

**Comment by kaylanx** [comment]
That was quick, thank you :]
