### ISSUE TITLE
iOS 9 seems to have added its own support for UICollectionView

### ISSUE THREAD

**Issue by lenkawell** [michaeltyson/TPKeyboardAvoiding#188]
As far as I can tell, UICollectionView (at least for flow layout and vertical scrolling) has been updated in iOS 9.0 to work the way UITableView does now and automatically increases the content size and scrolls to the first responder text field/view. I haven't found an Apple release note or doc change mentioning it yet, though.

As far as my app is concerned, that means that TPKeyboardAvoidingCollectionView is completely broken on iOS 9+. The content size gets reset to be too small when the keyboard disappears (e.g., cells at the bottom are no longer visible).

Since I load the TPKeyboardAvoidingCollectionView in a storyboard, I modified my version to pretty much avoid doing anything if the version is iOS 9.0 or above.

For example:

` -(void)awakeFromNib {
        if ([[NSProcessInfo processInfo] operatingSystemVersion].majorVersion < 9) {
           [self setup];
        }
    }`

**Comment by michaeltyson** [comment]
This should be all good now; TPKB disables on iOS 9.

**Comment by lenkawell** [comment]
Thanks!
