### ISSUE TITLE
After i've changed the textfield Height text becomes awkward.

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [michaeltyson/TPKeyboardAvoiding#189]
After i've changed the textfield Height which added in TPKeyboardAvoidingScrollView, when the cursor ends editing, the text animates to the top and become awkward.please help me. Thanks. I applied to the demo project also, it becomes the same way.

**Comment by Johnykutty** [comment]
Same issue for me, You got any resolution?

**Comment by Johnykutty** [comment]
T be more specific, This is happening me if the textfield focus going out for first time. Next time onwards no problem there. 
Adding short video: https://www.dropbox.com/s/j8lrz75g1ugrzvt/TpKeyboardTextfieldJump.mov?dl=0

**Comment by robdigital** [comment]
JohnyKutty: I'm seeing the exact problem with the text jumping after first edit just like your video. At first I thought it was just a weird iOS 9 thing. Please let us know if you find any solution.

**Comment by AyeChanPyaeSone** [comment]
Its also happens for me only in iOS 9.

**Comment by Johnykutty** [comment]
@michaeltyson Can you give a solution?. We are waiting for a solution for this. Because we are half way of development, but this issues screwed us.

**Comment by michaeltyson** [comment]
Hmm pretty sure the latest version already solves this. Can you verify you're using the latest?

**Comment by Johnykutty** [comment]
Thanks @michaeltyson :). Its not jumping after update to 1.2.10. Thanks again

**Comment by michaeltyson** [comment]
Great!
