### ISSUE TITLE
iPad long delay issue - UI is frozen

### ISSUE THREAD

**Issue by Skornos** [michaeltyson/TPKeyboardAvoiding#195]
Hi,

I must say I love this library ad it helps me tremendously. Byt now I am experiencing a strange issue while using iPad Air with iOS 9.0.2 0 - there is quite long delay between presenting keyboard and tap on the textfield. The whole UI gets frozen and you have to wait for 3 seconds before the keyboard pops up and the UI responses again.

I have to say that this is not a problem on iPhone 5s with the same iOS and simulator also doesn't have this problem.

I have tried your Sample Demo project and the issue is there. Also it only occurs only on the first presentation of the keyboard but the duration of this is rather annoying.

**Comment by michaeltyson** [comment]
Hi @Skornos - this looks like a debugger bug; if you start the app from the device, the problem doesn't exist. Also, if you pause the debugger during that delay, you'll see it's hanging inside gdb_image_notifier.

So, this is one for Apple: http://bugreport.apple.com
