### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by Errortype520** [michaeltyson/TPKeyboardAvoiding#206]
carthage update --platform iOS --no-use-binaries

*** Skipped building TPKeyboardAvoiding due to the error:
Dependency "TPKeyboardAvoiding" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/michaeltyson/TPKeyboardAvoiding/issues/new

**Comment by zurce** [comment]
Having the same issue here, any update ?

**Comment by michaeltyson** [comment]
I don't actually use Carthage, so I'm not really familiar with how it works. I'll happily accept a pull request to add support, if necessary.
