### ISSUE TITLE
Only works for one UITextField

### ISSUE THREAD

**Issue by kakubei** [michaeltyson/TPKeyboardAvoiding#216]
First of all, thanks for this, a great time-saver. However, I have an issue where the scroll only works for the first UITextField in my View Controller, not for the second one. 

Both TextFields have the delegate set as their View Controller. There is nothing different in these text fields, they both contain IBOutlets.

Any ideas? Thanks.

**Comment by michaeltyson** [comment]
You're most welcome! Hmm. Maybe share a little sample app that shows this?

**Comment by kakubei** [comment]
Please disregard. It turned out to be my fault, I needed to set at least one item in the scroll view with a bottom constraint to it in order for this to work.
