### ISSUE TITLE
Method possibly missing a [super awakeFromNib] call

### ISSUE THREAD

**Issue by dwby** [michaeltyson/TPKeyboardAvoiding#232]
Hey!
For Xcode 8 I get this warning message for:
TPKeyboardAvoidingScrollView.m
TPKeyboardAvoidingTableView.m
Doesn't seem to impact anything but would be good to know how if I should add 

`[super awakeFromNib];`
to 
`-(void)awakeFromNib`

Cheers

**Comment by alistairmcmillan** [comment]
From [Apple's API reference for awakeFromNib](https://developer.apple.com/reference/objectivec/nsobject/1402907-awakefromnib?language=objc):

> You must call the super implementation of awakeFromNib to give parent classes the opportunity to perform any additional initialization they require. Although the default implementation of this method does nothing, many UIKit classes provide non-empty implementations. You may call the super implementation at any point during your own awakeFromNib method.
