### ISSUE TITLE
Please update cocoapod. 

### ISSUE THREAD

**Issue by jkunzelman** [michaeltyson/TPKeyboardAvoiding#238]
I use TPKeyboardAvoiding thru cocoapods, it doesn't seem to be picking up new updates. The current pod still has a warning for missing [super awakeFromNib]

**Comment by michaeltyson** [comment]
Done!

**Comment by jhudsonWA** [comment]
Noticed some updates through June. Would love to get a new release and cocoapod released that has the changes since 2016
