### ISSUE TITLE
Increase Cocoa Pods Version

### ISSUE THREAD

**Issue by zerox1212** [michaeltyson/TPKeyboardAvoiding#261]
Please update the podspec so that running `pod update TPKeyboardAvoiding` will grab the latest code (which has some iOS 11 fixes in my case).

Cocoapods Version hasn't been updated in a year...

Current workaround is to directly reference git in the pod file:
`pod 'TPKeyboardAvoiding', :git => 'https://github.com/michaeltyson/'TPKeyboardAvoiding.git'`

**Comment by OliverDobner-flinc** [comment]
We are missing a new release, not only a pod spec update. 😏 I need this too.

**Comment by michaeltyson** [comment]
Done!
