### ISSUE TITLE
I have single textfield in single custom cell, i have used Tpkeyboardavoidingtableview class but next is not working

### ISSUE THREAD

**Issue by himanshu1261994** [michaeltyson/TPKeyboardAvoiding#268]

**Comment by jkmathew** [comment]
Have you set the delegate of the textfield?

**Comment by himanshu1261994** [comment]
Yes i have used, so i think that is the reason not able to go next right ?? It's ok now i'm using Tpkeyboard and IQKeyboardManager both.
Thanks
