### ISSUE TITLE
Advancing to Other Fields with the Next Keyboard Button Doesn't Work

### ISSUE THREAD

**Issue by cliftonlabrum** [michaeltyson/TPKeyboardAvoiding#29]
Great work on this!

Just one issue I've found. The Readme states: 

_"It also automatically hooks up 'Next' buttons on the keyboard to switch through the text fields."_

I added this to a UIScrollView that has fields in it, and I haven't been able to get this part to work. The scrollView adjustments with the keyboard work fine, but hitting Next on the fields doesn't do anything.

Thanks!

**Comment by robinmacharg** [comment]
This is quite simple to implement manually with a combination of `becomeFirstResponder()` (on all but the last field) and `resignFirstResponder()` (on the last field).  For instance (longhand swift):

    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        switch textField {
        case self.textField1:
            self.textField2.becomeFirstResponder()
        case self.textField2:
            self.textField3.becomeFirstResponder()
        case self.textField3:
            self.textField2.resignFirstResponder()
        }
    }

For larger numbers of controls a more scalable solution - an array of controls? - is probably desirable.  In the above I'd modify the Return button manually but again, code could achieve the same.  It might be worth pointing out the delegate-proviso on the Readme.
