### ISSUE TITLE
Avoid Xcode 12 warning -> move to iOS 9

### ISSUE THREAD

**Issue by tbechtum** [michaeltyson/TPKeyboardAvoiding#292]
Updated to latest version

pod 'TPKeyboardAvoiding'

### Usage Details
  - Language: Swift
  - Platform: iPhone
  - iOS Version: iOS 9 - 14

### Expected Behavior
Xcode 12 build without warnings, proposal to move target to iOS 9

### Actual Behavior
Xcode 12.x warning
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### Steps to Reproduce the Problem
  1. Use latest Xcode 12 or 12.0.1
  2. Use TPKeyboardAvoiding in a Swift project with target iOS 11

**Comment by tbechtum** [comment]
Please considerate that in my bigger project I am facing this waning for many external components and the it is difficult now for me to keep the overview of the relevant ones in order to resolve them.

Did you plan to move this project to iOS 9 already?
Thanks!

**Comment by nicoonguitar** [comment]
@tbechtum hello, you can try this patch solution, apparently the issue comes from CocoaPods:

```
# workaround solution for Xcode12 dropping iOS 8.0 support warning
 # cf. https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
     end
   end
 end
```

**Comment by tbechtum** [comment]
Thanks for your reply, but I need the deployment on iPhones. Seems to be a workaround. But are there any issues to move your support to iOS 9 and later (de-supporting iOS 8). Do you think you will loose clients?

**Comment by nicoonguitar** [comment]
> Thanks for your reply, but I need the deployment on iPhones. Seems to be a workaround. But are there any issues to move your support to iOS 9 and later (de-supporting iOS 8). Do you think you will loose clients?

It is indeed a workaround, but as stated, it is an issue related to CocoaPods. I can't help regarding your other questions because I'm not the creator of the framework.

@michaeltyson is this framework still maintained ? it could be interesting to help contribute to it, as I have been freely profiting from it the past years, if you are in need for help.

**Comment by tbechtum** [comment]
Hi,
hope to be more clear, I am asking to move the deployment target of this project to iOS 9 and later in order to avoid the Xcode 12 warnings. I will try this later as soon as possible in a fork and let you know. Thanks.

**Comment by michaeltyson** [comment]
> @michaeltyson is this framework still maintained ? it could be interesting to help contribute to it, as I have been freely profiting from it the past years, if you are in need for help.

It is, @nicoonguitar, just a bit infrequently as I don't use it any more myself. I've just merged a few pull requests and pushed an update though.

**Comment by tbechtum** [comment]
Hi thanks a lot for your work, updated now to the latest version 1.3.5, this warning 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0' disappeared and TPKeyboardAvoiding works fine.
