### ISSUE TITLE
Crash when TPKeyboardAvoiding*View parent view is deallocated while scrolling.

### ISSUE THREAD

**Issue by anlaital** [michaeltyson/TPKeyboardAvoiding#68]
If you deallocate the parent view of any of the TPKeyboardAvoiding*View objects while it's scrolling, you will get a EXC_BAD_ACCESS crash. This is caused by the following code (which is copy-pasted to all the three implementations):

``` objective-c
-(void)layoutSubviews 
// --snip--
[NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(TPKeyboardAvoiding_assignTextDelegateForViewsBeneathView:) object:self];
[self performSelector:@selector(TPKeyboardAvoiding_assignTextDelegateForViewsBeneathView:) withObject:self afterDelay:0.1];
```

performSelect increases the retain count of self in this case and since scrolling a view causes layoutSubviews to be called it gets queued to the run loop. The problem is apparent when you deallocate the parent view during this 0.1s time slot.

**Comment by farri** [comment]
still crashing 

(void)TPKeyboardAvoiding_initializeView:(UIView)view {
if ( [view isKindOfClass:[UITextField class]]  /// here it crashes
&& ((UITextField)view).returnKeyType == UIReturnKeyDefault
&& (![(UITextField)view delegate] || [(UITextField)view delegate] == (id)self) ) {
[(UITextField*)view setDelegate:(id)self];
UIView *otherView = nil;
CGFloat minY = CGFLOAT_MAX;
[self TPKeyboardAvoiding_findTextFieldAfterTextField:view beneathView:self minY:&minY foundView:&otherView];

if ( otherView ) {
    ((UITextField*)view).returnKeyType = UIReturnKeyNext;
} else {
    ((UITextField*)view).returnKeyType = UIReturnKeyDone;
}
}
}

**Comment by farri** [comment]
if (![(UITextField*)view delegate] || [(UITextField*)view delegate] == (id<UITextFieldDelegate>)self) 

crash is here

**Comment by Cyclesathish** [comment]
I have found one reason for the crash:

Create class level object for the Parentview.

For me it worked

**Comment by peterdk** [comment]
I am running into this bug only on iOS 8, on iOS 9 it all works ok. It happens when I have a textfield selected and editing the content, and then press the back button of the nav controller.

`- (void)TPKeyboardAvoiding_initializeView:(UIView*)view {
    if ( [view isKindOfClass:[UITextField class]]
            && ((UITextField*)view).returnKeyType == UIReturnKeyDefault
            && (![(UITextField*)view delegate] //CRASH HERE EXC_BAD_ACCESS
                ||
                [(UITextField*)view delegate] == (id<UITextFieldDelegate>)self) ) {
`
