### ISSUE TITLE
[TPKeyboardAvoidingScrollView TPKeyboardAvoiding_updateContentInset]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mattquiros** [michaeltyson/TPKeyboardAvoiding#75]
I added TPKeyboardAvoidingScrollView via CocoaPods and I'm building my view controller programatically. Whenever the view controller is about to be shown, it throws this error:

```
[TPKeyboardAvoidingScrollView TPKeyboardAvoiding_updateContentInset]: unrecognized selector sent to instance
```

I fixed the issue by adding `UIScrollView+TPKeyboardAvoidingAdditions.m` to my target's Build Phases > Compile Sources. But I shouldn't have to do that, right? Is this some form of incompatibility with CocoaPods? Thanks.

**Comment by foffux** [comment]
Same issue for me. Solve added "UIScrollView+TPKeyboardAvoidingAdditions.m", but not good at all.

**Comment by foffux** [comment]
Seems to be an issue related to cocoa pods and iOS 8 SDK interaction. Please red this:

http://stackoverflow.com/questions/10442653/unrecognized-selector-calling-category-method-in-static-ios-library

I think this could be a good workaround to avoid wasting too much time.

**Comment by michaeltyson** [comment]
It sounds like your project's not set up correctly. Pod should create an Xcode workspace, containing your app and the installed pods, and it should add the "-ObjC" flag to your build process via the xcconfig files in Pods/Target Support Files/Pods. That flag makes Xcode load all symbols from the static libraries that Cocoapods builds, which avoids the problem you describe.

You can test this out by creating a new Xcode project, then creating a Podfile in the project folder and running pod install.
